### ISSUE TITLE
Given icon is not a category!

### ISSUE THREAD

**Issue by TechTailor** [erikzimmermann/WarpSystem-IssueTracker#213]
Okay so was testing out this plugin on my server before I ultimately decide to purchase the premium version, however, for some reason its not working atm. This is the error from the log file.

```
java.lang.IllegalArgumentException: Given icon is not a category!
	at de.codingair.warpsystem.spigot.features.warps.managers.IconManager.getIcons(IconManager.java:565)
	at de.codingair.warpsystem.spigot.features.warps.managers.IconManager.clean(IconManager.java:362)
	at de.codingair.warpsystem.spigot.features.warps.managers.IconManager.load(IconManager.java:323)
	at de.codingair.warpsystem.spigot.base.managers.DataManager.load(DataManager.java:32)
	at de.codingair.warpsystem.spigot.base.WarpSystem.onEnable(WarpSystem.java:165)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
	at java.lang.Thread.run(Thread.java:813)

```

```
java.lang.IllegalArgumentException: Given icon is not a category!
	at de.codingair.warpsystem.spigot.features.warps.managers.IconManager.getIcons(IconManager.java:565)
	at de.codingair.warpsystem.spigot.features.warps.managers.IconManager.clean(IconManager.java:362)
	at de.codingair.warpsystem.spigot.features.warps.managers.IconManager.load(IconManager.java:323)
	at de.codingair.warpsystem.spigot.base.managers.DataManager.load(DataManager.java:32)
	at de.codingair.warpsystem.spigot.base.WarpSystem.onEnable(WarpSystem.java:165)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
	at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62)
	at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127)
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800)
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$4106.00000000F4088250.run(Unknown Source)
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929)
	at java.lang.Thread.run(Thread.java:813)

```

Would appreciate if you can share a fix for this.

Thanks & Regards.

**Comment by TechTailor** [comment]
Okay, as discussed on discord, I have replicated the issue and uploading a before & after (error) file for ActionIcons.yml

I have same number of icons/warps set, the only difference between the 2 is me adding some lore to the warps and rearranging the positions of the icons. But as soon as I restart, I get the above error thrown. 

As you can see in the file with the error, it shows 13 items when I only have 8 set (a few of them are getting duplicated).
[ActionIcons (Before-Error).txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/3901120/ActionIcons.Before-Error.txt)
[ActionIcons (With Error).txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/3901121/ActionIcons.With.Error.txt)
