### ISSUE TITLE
Issue with RTP command in WarpSystem

### ISSUE THREAD

**Issue by jj136975** [erikzimmermann/WarpSystem-IssueTracker#282]
I have this error when I type /rtp go

[16:43:27] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_242]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_242]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [paper.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:773) [paper.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:712) [paper.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:615) [paper.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Can you help me please ?

**Comment by erikzimmermann** [comment]
Is this your entire exception message?

And some information would be great: Plugin version, Minecraft version, Server type (Spigot, Paper)

**Comment by jj136975** [comment]
yes, this is the entire message. About the plugin it's your lastest version, running on AtomSpigot (paper fork) 1.8.8

**Comment by erikzimmermann** [comment]
Thank you. I'm on it

**Comment by erikzimmermann** [comment]
Please add me on Discord (CodingAir#0281). Would be great if you could test a hotfix.

**Comment by jj136975** [comment]
I already added you (jj136975#5850)
