### ISSUE TITLE
[WarpGUI] Right-clicking "Help"

### ISSUE THREAD

**Issue by OfficialTheosis** [erikzimmermann/WarpSystem-IssueTracker#358]
Title says it all pretty much.
```[13:34:10] [Server thread/ERROR]: Could not pass event InventoryClickEvent to WarpSystem v4.2.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2148) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at de.codingair.warpsystem.spigot.base.guis.options.pages.PWarpGUI$1.craftItem(PWarpGUI.java:42) ~[?:?]
        at de.codingair.codingapi.player.gui.inventory.gui.simple.SyncButton.update(SyncButton.java:29) ~[?:?]
        at de.codingair.codingapi.player.gui.inventory.gui.simple.SyncButton.<init>(SyncButton.java:10) ~[?:?]
        at de.codingair.codingapi.player.gui.inventory.gui.simple.SyncButton.<init>(SyncButton.java:14) ~[?:?]
        at de.codingair.warpsystem.spigot.base.guis.options.pages.PWarpGUI$1.<init>(PWarpGUI.java:39) ~[?:?]
        at de.codingair.warpsystem.spigot.base.guis.options.pages.PWarpGUI.initialize(PWarpGUI.java:39) ~[?:?]
        at de.codingair.warpsystem.spigot.base.guis.options.pages.PWarpGUI.<init>(PWarpGUI.java:31) ~[?:?]
        at de.codingair.warpsystem.spigot.base.guis.options.GOptions.<init>(GOptions.java:50) ~[?:?]
        at de.codingair.warpsystem.spigot.base.guis.options.OptionsGUI.<init>(OptionsGUI.java:15) ~[?:?]
        at de.codingair.warpsystem.spigot.features.warps.guis.GWarps$3.onClick(GWarps.java:229) ~[?:?]
        at de.codingair.codingapi.player.gui.GUIListener.onInvClickEvent(GUIListener.java:279) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-aae46f8]
        ... 17 more```

**Comment by erikzimmermann** [comment]
I just updated my resource... nooo D:

Thank you for your bugreport!

**Comment by erikzimmermann** [comment]
Please contact me via Discord (CodingAir# 0281).
