### ISSUE TITLE
NPE on Shutdown

### ISSUE THREAD

**Issue by Andre601** [erikzimmermann/WarpSystem-IssueTracker#362]
**Describe the bug**
WarpSystem throwed this NullPointerException when it was disabling:
https://paste.helpch.at/exigopamin.css

**To Reproduce**
1. Have latest WarpSystem version (4.2.6)
2. Start server
3. Stop server

**Expected behavior**
The plugin should disable as normal

**Screenshots**

-

**Additional context**
Running PaperMC 1.15.2

**Comment by erikzimmermann** [comment]
```
java.lang.NullPointerException: null
        at de.codingair.warpsystem.spigot.base.managers.VanishManager.onDisconnect(VanishManager.java:59) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at de.codingair.warpsystem.spigot.base.WarpSystem.onDisable(WarpSystem.java:362) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-284]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.15.2.jar:git-Paper-284]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-284]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.15.2.jar:git-Paper-284]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.15.2.jar:git-Paper-284]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:406) ~[patched_1.15.2.jar:git-Paper-284]
        at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:741) ~[patched_1.15.2.jar:git-Paper-284]
        at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752) ~[patched_1.15.2.jar:git-Paper-284]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:1005) ~[patched_1.15.2.jar:git-Paper-284]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
