### ISSUE TITLE
NullPointerException for PlayerWalkEvent when using /portal edit

### ISSUE THREAD

**Issue by Andre601** [erikzimmermann/WarpSystem-IssueTracker#412]
**Describe the bug**
When using `/portal edit` does WarpSystem throw the below error.
Note that you can still edit the portal and that I (so far) didn't encounter any limitations or (visual) errors outside of a hologram not showing when teleporting between dimensions.

```
[04:36:30 INFO]: Andre_601 issued server command: /portals edit
[04:37:11 ERROR]: Could not pass event PlayerWalkEvent to WarpSystem v4.2.7
java.lang.NullPointerException: null
        at net.minecraft.server.v1_16_R1.World.isOutsideWorld(World.java:270) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.World.getType(World.java:715) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.PlayerList.moveToWorld(PlayerList.java:857) ~[patched_1.16.1.jar:git-Paper-99]
        at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleport(CraftPlayer.java:813) ~[patched_1.16.1.jar:git-Paper-99]
        at de.codingair.warpsystem.spigot.features.portals.utils.PortalDestinationAdapter.teleport(PortalDestinationAdapter.java:34) ~[?:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.destinations.Destination.teleport(Destination.java:107) ~[?:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.Teleport$3.accept(Teleport.java:277) ~[?:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.Teleport.teleport(Teleport.java:305) ~[?:?]
        at de.codingair.warpsystem.spigot.base.managers.TeleportManager$5.accept(TeleportManager.java:299) ~[?:?]
        at de.codingair.warpsystem.spigot.base.managers.TeleportManager.teleport(TeleportManager.java:306) ~[?:?]
        at de.codingair.warpsystem.spigot.base.utils.featureobjects.FeatureObject.perform(FeatureObject.java:119) ~[?:?]
        at de.codingair.warpsystem.spigot.features.portals.utils.Portal.perform(Portal.java:232) ~[?:?]
        at de.codingair.warpsystem.spigot.features.portals.managers.PortalManager$1.onEnter(PortalManager.java:224) ~[?:?]
        at de.codingair.warpsystem.spigot.features.portals.listeners.PortalListener.onWalk(PortalListener.java:56) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor149.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-99]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-99]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-99]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-99]
        at de.codingair.codingapi.server.events.WalkListener.onWalk(WalkListener.java:24) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor126.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-99]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-99]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-99]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1163) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-99]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-99]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**To Reproduce**
1. Run `/portal edit`
2. Walk to the portal you want to edit
3. See error

**Expected behavior**
No error should appear in the console.

**Screenshots**

**Additional context**
I'm running the plugin on a PaperMC version (build 99 for MC 1.16.1)

**Comment by Andre601** [comment]
Update: This also randomly happens for pretty much any other time someone uses the portal, not just when you edit one.

**Comment by erikzimmermann** [comment]
Does this issue still appear on latest spigot/paper builds?

**Comment by Andre601** [comment]
I didn't see any issues in the past days, but I mainly checked the shutdown

**Comment by erikzimmermann** [comment]
Alright. Gonna close this for now. Please comment here if you get further issues with it.
