### ISSUE TITLE
Null pointer while creating warp caused by getSkinId

### ISSUE THREAD

**Issue by divios** [erikzimmermann/WarpSystem-IssueTracker#434]
When i try to create a warp this error pops up on the console. I'm on 1.16.1, on a survival server behind bungee and using skinsrestorer on bungee mode

https://pastebin.com/mNJnn7GM

**Comment by erikzimmermann** [comment]
```
[21:25:55 WARN]: [WarpSystem] Task #7754 for WarpSystem v4.2.8-free generated an exception
java.lang.NullPointerException: null
        at de.codingair.warpsystem.spigot.base.managers.HeadManager.getSkinId(HeadManager.java:24) ~[?:?]
        at de.codingair.warpsystem.spigot.features.playerwarps.utils.PlayerWarp.getStandardItemBuilder(PlayerWarp.java:430) ~[?:?]
        at de.codingair.warpsystem.spigot.features.playerwarps.utils.PlayerWarp.resetItem(PlayerWarp.java:424) ~[?:?]
        at de.codingair.warpsystem.spigot.features.playerwarps.utils.PlayerWarp.<init>(PlayerWarp.java:74) ~[?:?]
        at de.codingair.warpsystem.spigot.features.playerwarps.commands.CPlayerWarps.createPlayerWarp(CPlayerWarps.java:335) ~[?:?]
        at de.codingair.warpsystem.spigot.features.playerwarps.commands.CPlayerWarps.access$000(CPlayerWarps.java:33) ~[?:?]
        at de.codingair.warpsystem.spigot.features.playerwarps.commands.CPlayerWarps$11.lambda$onClose$0(CPlayerWarps.java:321) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by erikzimmermann** [comment]
@divios Please contact me on Discord (CodingAir#0281) for a possible hotfix.
