### ISSUE TITLE
[GlobalWarps] Initializing issues

### ISSUE THREAD

**Issue by erikzimmermann** [erikzimmermann/WarpSystem-IssueTracker#459]
Contact: **terbin**
```
[08:03:22 WARN]: [WarpSystem] Task #339 for WarpSystem v4.2.10 generated an exception
java.lang.IllegalStateException: There is already a SpecialCommandComponent!
        at de.codingair.codingapi.server.commands.builder.CommandComponent.addChild(CommandComponent.java:56) ~[?:?]
        at de.codingair.warpsystem.spigot.features.globalwarps.commands.CGlobalWarp.onConnect(CGlobalWarp.java:53) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
        at de.codingair.warpsystem.spigot.base.WarpSystem.setOnBungeeCord(WarpSystem.java:558) ~[?:?]
        at de.codingair.warpsystem.spigot.base.listeners.BungeeBukkitListener.lambda$onReceive$1(BungeeBukkitListener.java:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by erikzimmermann** [comment]
Same as #475
