### ISSUE TITLE
[PlayerWarps] Owner will be nulled (on renaming the warp)

### ISSUE THREAD

**Issue by erikzimmermann** [erikzimmermann/WarpSystem-IssueTracker#481]
```
Could not pass event InventoryClickEvent to WarpSystem v4.2.11-hotfix-2
java.lang.NullPointerException: null
at de.codingair.warpsystem.spigot.features.playerwarps.utils.PlayerWarp.isOwner(PlayerWarp.java:473) ~[?:?]
at de.codingair.warpsystem.spigot.features.playerwarps.utils.PlayerWarp.isOwner(PlayerWarp.java:469) ~[?:?]
at de.codingair.warpsystem.spigot.features.playerwarps.utils.PlayerWarp.perform(PlayerWarp.java:111) ~[?:?]
at de.codingair.warpsystem.spigot.features.playerwarps.guis.list.filters.OwnWarpFilter$1.onClick(OwnWarpFilter.java:61) ~[?:?]
at de.codingair.codingapi.player.gui.inventory.gui.simple.Button.onClick(Button.java:27) ~[?:?]
at de.codingair.codingapi.player.gui.GUIListener.onInvClickEvent(GUIListener.java:256) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor945.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-214]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-214]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-214]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2427) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-214]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-214]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

**Comment by erikzimmermann** [comment]
Happens only on a BungeeCord network witout WarpSystem installed on the Bunge.
Fixed with new build.
