### ISSUE TITLE
[RTP] NullPointer

### ISSUE THREAD

**Issue by erikzimmermann** [erikzimmermann/WarpSystem-IssueTracker#483]
```
[02:14:33 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rtp' in plugin WarpSystem v4.2.11-free_hotfix-3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-91]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-91]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1259) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-91]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-91]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
        at de.codingair.warpsystem.spigot.features.randomteleports.managers.RandomTeleporterManager.getBoughtTeleports(RandomTeleporterManager.java:453) ~[?:?]
        at de.codingair.warpsystem.spigot.features.randomteleports.managers.RandomTeleporterManager.canTeleport(RandomTeleporterManager.java:246) ~[?:?]
        at de.codingair.warpsystem.spigot.features.randomteleports.managers.RandomTeleporterManager.tryToTeleport(RandomTeleporterManager.java:373) ~[?:?]
        at de.codingair.warpsystem.spigot.features.randomteleports.managers.RandomTeleporterManager.tryToTeleport(RandomTeleporterManager.java:318) ~[?:?]
        at de.codingair.warpsystem.spigot.features.randomteleports.commands.CRandomTp$7.runCommand(CRandomTp.java:171) ~[?:?]
        at de.codingair.codingapi.server.commands.builder.CommandBuilder.onCommand(CommandBuilder.java:229) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-91]
        ... 18 more
```

**Comment by erikzimmermann** [comment]
Same as #481
