### ISSUE TITLE
Internal Server Error on /pwarps

### ISSUE THREAD

**Issue by RedZephon** [erikzimmermann/WarpSystem-IssueTracker#599]
Some users are reporting that when they attempt to open the pwarps gui (/pwarps) they get an internal server error. Both of these users have an absurd number of warps, like 30-50. 

On my 2 accounts that have less then 10 i dont see this issue.

The console outputs only "null" when the command is run. In chat for the players they get "command can not be executed due to internal server error"

**Comment by erikzimmermann** [comment]
```
[13:54:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pwarp' in plugin WarpSystem v5.0.1_Hotfix-11
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-468]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-468]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-468]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 27
        at java.util.Arrays$ArrayList.set(Arrays.java:3846) ~[?:1.8.0_275]
        at net.minecraft.server.v1_16_R3.NonNullList.set(SourceFile:53) ~[patched_1.16.5.jar:git-Paper-468]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:108) ~[patched_1.16.5.jar:git-Paper-468]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventory.setItem(CraftInventory.java:99) ~[patched_1.16.5.jar:git-Paper-468]
        at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.gui.Interface.setItem(Interface.java:669) ~[?:?]
        at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.gui.GUI.setItem(GUI.java:426) ~[?:?]
        at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.gui.Interface.addButton(Interface.java:99) ~[?:?]
        at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.gui.GUI.addButton(GUI.java:350) ~[?:?]
        at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.gui.simple.Page.initialize(Page.java:55) ~[?:?]
        at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.gui.simple.SimpleGUI.initialize(SimpleGUI.java:76) ~[?:?]
        at de.codingair.warpsystem.spigot.features.playerwarps.guis.list.PWList.initialize(PWList.java:80) ~[?:?]
        at de.codingair.warpsystem.spigot.features.playerwarps.guis.list.PWList.<init>(PWList.java:64) ~[?:?]
        at de.codingair.warpsystem.spigot.features.playerwarps.commands.CPlayerWarp$1.runCommand(CPlayerWarp.java:46) ~[?:?]
        at de.codingair.warpsystem.lib.codingapi.server.commands.builder.CommandBuilder.onCommand(CommandBuilder.java:227) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-468]
        ... 19 more
```
