### ISSUE TITLE
5.0.2 Warp BUG #2

### ISSUE THREAD

**Issue by pupshadow** [erikzimmermann/WarpSystem-IssueTracker#619]
Found  a bug with the new update 5.0.2: When you start a server up and wait about 3 min after it shows this bug.

Version:

This server is running Paper version git-Paper-629 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-602 (MC: 1.16.5)

Plugins:

Plugins (51): AdvancedNMotd, AntiXRay, AutoRestart*, BentoBox, ChestSort, ClearLag, CMI, CMILib, CoreProtect, DeadChest, dynmap*, eZProtector, EZRanksPro, floodgate, Geyser-Spigot, Harbor, Lands, LevelledMobs, LibsDisguises, LuckPerms, LWC, MineConnect, MoneyFromMobs, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MythicLib, MythicMobs, MythicMobsExtension, PlotSquared, PlugMan, ProtocolLib, PureTickets, ServerSigns, ShatteredCore, ShatteredScrolls, SkinsRestorer, StaffFacilities, TreeAssist, Vault, ViaBackwards, ViaRewind, ViaVersion, Vivecraft-Spigot-Extensions, VoidGenerator, WarpSystem, WorldBorderAPI, WorldEdit, WorldGeneratorApi, WorldGuard, WorldGuardEvents

Issue log:

[03:03:34 WARN]: java.net.SocketTimeoutException: Read timed out
[03:03:34 WARN]: at java.base/java.net.SocketInputStream.socketRead0(Native Method)
[03:03:34 WARN]: at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
[03:03:34 WARN]: at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
[03:03:34 WARN]: at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
[03:03:34 WARN]: at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
[03:03:34 WARN]: at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
[03:03:34 WARN]: at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
[03:03:34 WARN]: at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
[03:03:34 WARN]: at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1359)
[03:03:34 WARN]: at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1268)
[03:03:34 WARN]: at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
[03:03:34 WARN]: at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
[03:03:34 WARN]: at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
[03:03:34 WARN]: at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[03:03:34 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[03:03:34 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[03:03:34 WARN]: at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[03:03:34 WARN]: at java.base/java.net.URL.openStream(URL.java:1140)
[03:03:34 WARN]: at de.codingair.warpsystem.spigot.base.utils.updates.UpdateNotifier.readBody(UpdateNotifier.java:69)
[03:03:34 WARN]: at de.codingair.warpsystem.spigot.base.utils.updates.UpdateNotifier.read(UpdateNotifier.java:26)
[03:03:34 WARN]: at de.codingair.warpsystem.spigot.base.utils.updates.UpdateReader.lambda$start$0(UpdateReader.java:13)
[03:03:34 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[03:03:34 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[03:03:34 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[03:03:34 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[03:03:34 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

**Comment by erikzimmermann** [comment]
Same as #616
