### ISSUE TITLE
[PlayerWarps] Error if categories classes is more than 12

### ISSUE THREAD

**Issue by sleepyr-sa** [erikzimmermann/WarpSystem-IssueTracker#626]
**Describe the bug**
Receive error when player try to edit their playerwarp via gui if categories classes is more than 12

**To Reproduce**
1. Create more than 12 Classes in Categories (PlayerWarpConfig.yml)
2. /pwarps
3. right-click to edit the warp
4. error and no GUI popup

**Expected behavior**
1. /pwarps
2. right-click to edit the warp
3. popup edit GUI

**Screenshots**
```
[16:01:24] [Server thread/ERROR]: Could not pass event InventoryClickEvent to WarpSystem v5.0.2_Hotfix-1
java.lang.ArrayIndexOutOfBoundsException: Index 12 out of bounds for length 12
	at de.codingair.warpsystem.spigot.features.playerwarps.guis.editor.pages.PClasses.initialize(PClasses.java:103) ~[?:?]
	at de.codingair.warpsystem.spigot.features.playerwarps.guis.editor.pages.PClasses.<init>(PClasses.java:34) ~[?:?]
	at de.codingair.warpsystem.spigot.features.playerwarps.guis.editor.PWEditor.<init>(PWEditor.java:93) ~[?:?]
	at de.codingair.warpsystem.spigot.features.playerwarps.guis.editor.PWEditor.<init>(PWEditor.java:50) ~[?:?]
	at de.codingair.warpsystem.spigot.features.playerwarps.guis.list.filters.OwnWarpFilter$1.onClick(OwnWarpFilter.java:63) ~[?:?]
	at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.gui.simple.Button.onClick(Button.java:27) ~[?:?]
	at de.codingair.warpsystem.lib.codingapi.player.gui.GUIListener.onInvClickEvent(GUIListener.java:266) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor586.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2610) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1322) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Tuinity-"a539774"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Additional context**
Work normally if classes is less than 12

**Discord contact**: `sleepy_#0001`

**Comment by erikzimmermann** [comment]
Sorry, but 12 categories are the maximum the GUI can handle... I'll handle the error but cannot do more than that.
