### ISSUE TITLE
Update 1.17.1 errors

### ISSUE THREAD

**Issue by p1xmedia** [erikzimmermann/WarpSystem-IssueTracker#638]
[18:17:33] [Server thread/INFO]: fli4l issued server command: /warp
[18:17:33] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'warp' in plugin WarpSystem v5.0.3
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-85]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-85]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-85]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2165) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1976) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1957) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
    at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-85]
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-85]
    at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-85]
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-85]
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-85]
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-85]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-85]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-85]
    at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: Can not set net.minecraft.world.entity.Entity field net.minecraft.world.item.ItemStack.w to net.minecraft.nbt.NBTTagCompound
    at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
    at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
    at jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[?:?]
    at java.lang.reflect.Field.set(Field.java:793) ~[?:?]
    at de.codingair.warpsystem.lib.codingapi.server.reflections.IReflection$5.set(IReflection.java:234) ~[?:?]
    at de.codingair.warpsystem.lib.codingapi.tools.nbt.NBTTagCompound.<init>(NBTTagCompound.java:30) ~[?:?]
    at de.codingair.warpsystem.lib.codingapi.tools.items.ItemBuilder.<init>(ItemBuilder.java:88) ~[?:?]
    at de.codingair.warpsystem.spigot.features.warps.guis.GWarps.initialize(GWarps.java:216) ~[?:?]
    at de.codingair.warpsystem.spigot.features.warps.guis.GWarps.<init>(GWarps.java:188) ~[?:?]
    at de.codingair.warpsystem.spigot.features.warps.guis.GWarps.<init>(GWarps.java:67) ~[?:?]
    at de.codingair.warpsystem.spigot.features.warps.guis.GWarps.<init>(GWarps.java:62) ~[?:?]
    at de.codingair.warpsystem.spigot.features.warps.guis.GWarps.<init>(GWarps.java:57) ~[?:?]
    at de.codingair.warpsystem.spigot.features.warps.commands.CWarps.run(CWarps.java:113) ~[?:?]
    at de.codingair.warpsystem.spigot.features.simplewarps.commands.CWarp$1.runCommand(CWarp.java:57) ~[?:?]
    at de.codingair.warpsystem.lib.codingapi.server.commands.builder.CommandBuilder.onCommand(CommandBuilder.java:227) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-85]
    ... 21 more

AND:

[16:17:59 ERROR]: [WarpSystem] Error at saving data! Exception:

[16:17:59 WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.entity.Entity field net.minecraft.world.item.ItemStack.w to net.minecraft.nbt.NBTTagCompound
[16:17:59 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[16:17:59 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[16:17:59 WARN]:        at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
[16:17:59 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:793)
[16:17:59 WARN]:        at de.codingair.warpsystem.lib.codingapi.server.reflections.IReflection$5.set(IReflection.java:234)
[16:17:59 WARN]:        at de.codingair.warpsystem.lib.codingapi.tools.nbt.NBTTagCompound.<init>(NBTTagCompound.java:30)
[16:17:59 WARN]:        at de.codingair.warpsystem.lib.codingapi.tools.items.ItemBuilder.<init>(ItemBuilder.java:88)
[16:17:59 WARN]:        at de.codingair.warpsystem.lib.codingapi.tools.io.utils.SpigotDataMask.put(SpigotDataMask.java:24)
[16:17:59 WARN]:        at de.codingair.warpsystem.spigot.features.warps.managers.IconManager.save(IconManager.java:198)
[16:17:59 WARN]:        at de.codingair.warpsystem.spigot.base.managers.DataManager.save(DataManager.java:69)
[16:17:59 WARN]:        at de.codingair.warpsystem.spigot.base.WarpSystem.save(WarpSystem.java:425)
[16:17:59 WARN]:        at de.codingair.warpsystem.spigot.base.WarpSystem.lambda$startAutoSaver$2(WarpSystem.java:386)
[16:17:59 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[16:17:59 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[16:17:59 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:17:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[16:17:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[16:17:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[16:17:59 ERROR]: [WarpSystem]

**Comment by erikzimmermann** [comment]
Has the same source as #642
