### ISSUE TITLE
[GWARP] Server crashing when warping to gwarp.

### ISSUE THREAD

**Issue by Jauska** [erikzimmermann/WarpSystem-IssueTracker#641]
**Describe the bug**
Server crashes after I try to warp to an gwarp in the same server.

**To Reproduce**
1. Execute command /gwarps list
2. Click on a gwarp that is located in the same server as you are connected to.
3. Server Crashes!

**Expected behavior**
I am teleported to the warp without server crashes.

**Screenshots**
None

**Additional context**
Plugins (39): AdvancedModreq, AdvancedPortals, AntiXrayHeuristics, ArmorStandEditor, Chunkmaster, Citizens, CMILib, CoreProtect, DeathChestPro, eGlow, Elevator, Essentials, FredashaySpigotArmorStandProtect, HeadDatabase, HolographicDisplays, HolographicExtension, InventoryRollback, Jobs, LiteBans, LuckPerms, mcMMO, MysqlPlayerDataBridge, OpenInv, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, SkQuery, Skript, SmoothSleep, UltimateTimber, Vault, VentureChat, Votifier, VoxelSniper, WarpSystem, WhatPlugin*, WorldEdit, WorldGuard
Jar: PaperSpigot 1.17
Plugin version: 5.0.3-Hotfix1
Proxy: Velocity
Log:
[2021-06-30-6 (1).log](https://github.com/CodingAir/WarpSystem-IssueTracker/files/6786036/2021-06-30-6.1.log)

**Discord contact**: Jauska # 0001
Feel free to @ me or private message on Discord if you need more information.

**Comment by erikzimmermann** [comment]
You have to update PlaceholderAPI.

Included in log:
```
[18:03:14] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.MinecraftServer
[18:03:14] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
[18:03:14] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[18:03:14] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[18:03:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[18:03:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[18:03:14] [Server thread/WARN]: 	at com.extendedclip.papi.expansion.server.ServerExpansion.<init>(ServerExpansion.java:64)
[18:03:14] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:03:14] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[18:03:14] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:03:14] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:03:14] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:03:14] [Server thread/WARN]: 	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.createExpansionInstance(LocalExpansionManager.java:336)
[18:03:14] [Server thread/WARN]: 	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:138)
[18:03:14] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[18:03:14] [Server thread/WARN]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[18:03:14] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[18:03:14] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[18:03:14] [Server thread/WARN]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[18:03:14] [Server thread/WARN]: 	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:257)
[18:03:14] [Server thread/WARN]: 	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
[18:03:14] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[18:03:14] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
[18:03:14] [Server thread/WARN]: 	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$2(LocalExpansionManager.java:288)
[18:03:14] [Server thread/WARN]: 	at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46)
[18:03:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[18:03:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[18:03:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1127)
[18:03:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[18:03:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```
