### ISSUE TITLE
Portals with Holgrams dont work after editing

### ISSUE THREAD

**Issue by TNProTV** [erikzimmermann/WarpSystem-IssueTracker#643]
When you try to edit a portal with a Hologram than it broke the portal an no gui is showing

Error Text:

```
[17:01:46 WARN]: [WarpSystem] Task #1041 for WarpSystem v5.0.4 generated an exception
java.lang.NullPointerException: Cannot invoke "de.codingair.warpsystem.lib.codingapi.server.reflections.IReflection$ConstructorAccessor.newInstance(Object[])" because "con" is null
        at de.codingair.warpsystem.lib.codingapi.player.Hologram$HologramPackets.destroy(Hologram.java:610) ~[?:?]
        at de.codingair.warpsystem.lib.codingapi.player.Hologram.destroy(Hologram.java:361) ~[?:?]
        at de.codingair.warpsystem.lib.codingapi.player.Hologram.update(Hologram.java:264) ~[?:?]
        at de.codingair.warpsystem.lib.codingapi.player.Hologram.update(Hologram.java:236) ~[?:?]
        at de.codingair.warpsystem.lib.codingapi.player.Hologram$2.run(Hologram.java:178) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-97]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Paper-97]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-97]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-97]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-97]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-97]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-97]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

Discord contact: TNPro93#3491

**Comment by erikzimmermann** [comment]
Fixed with #651
