### ISSUE TITLE
Holograms will not be destroyed on latest version

### ISSUE THREAD

**Issue by CraftJunkies** [erikzimmermann/WarpSystem-IssueTracker#651]
```
[23:46:44 ERROR]: Could not pass event InventoryClickEvent to WarpSystem v5.0.4
java.lang.NullPointerException: Cannot invoke "de.codingair.warpsystem.lib.codingapi.server.reflections.IReflection$ConstructorAccessor.newInstance(Object[])" because "<local3>" is null
        at de.codingair.warpsystem.lib.codingapi.player.Hologram$HologramPackets.destroy(Hologram.java:610) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.lib.codingapi.player.Hologram.destroy(Hologram.java:361) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.lib.codingapi.player.Hologram.update(Hologram.java:264) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.lib.codingapi.player.Hologram.update(Hologram.java:236) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.lib.codingapi.player.Hologram.update(Hologram.java:232) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.spigot.features.portals.utils.Hologram.hide(Hologram.java:58) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.spigot.features.portals.utils.Portal.update(Portal.java:457) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.spigot.features.portals.utils.Portal.setVisible(Portal.java:472) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.spigot.features.portals.utils.Portal.destroy(Portal.java:189) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.spigot.features.portals.managers.PortalManager$1$1.accept(PortalManager.java:186) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.spigot.features.portals.managers.PortalManager$1$1.accept(PortalManager.java:182) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.spigot.features.portals.guis.DeleteGUI$1.accept(DeleteGUI.java:14) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.spigot.features.portals.guis.DeleteGUI$1.accept(DeleteGUI.java:11) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.guis.ConfirmGUI$3.onClick(ConfirmGUI.java:96) ~[WarpSystem.jar:?]
        at de.codingair.warpsystem.lib.codingapi.player.gui.GUIListener.onInvClickEvent(GUIListener.java:266) ~[WarpSystem.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor237.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1345]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1345]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1345]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2857) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1369) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Purpur-1345]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1345]
        at java.lang.Thread.run(Thread.java:831) [?:?]

```

Go into editmode of any portal with hologram/try delete it
Latest purpur 1.17.1 and WarpSystem

**Comment by CraftJunkies** [comment]
Portals are not editable or deleteable
