### ISSUE TITLE
Exception when clicking ActionIcon on 1.12.2

### ISSUE THREAD

**Issue by terbin** [erikzimmermann/WarpSystem-IssueTracker#654]
**Describe the bug**
Paper 1.12.2
WarpSystem Premium 5.0.5

Clicking on an ActionIcon in the main warps GUI causes the following error:

```
[10:09:06] [Server thread/ERROR]: Could not pass event InventoryClickEvent to WarpSystem v5.0.5
org.bukkit.event.EventException: null
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_301]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_301]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.NullPointerException
    at de.codingair.warpsystem.lib.codingapi.tools.items.ItemBuilder.<init>(ItemBuilder.java:135) ~[?:?]
    at de.codingair.warpsystem.lib.codingapi.tools.items.ItemBuilder.<init>(ItemBuilder.java:160) ~[?:?]
    at de.codingair.warpsystem.lib.codingapi.tools.items.ItemBuilder.<init>(ItemBuilder.java:183) ~[?:?]
    at de.codingair.warpsystem.spigot.features.warps.guis.GWarps.initialize(GWarps.java:260) ~[?:?]
    at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.gui.GUI.reinitialize(GUI.java:129) ~[?:?]
    at de.codingair.warpsystem.spigot.features.warps.guis.GWarps$6.onClick(GWarps.java:354) ~[?:?]
    at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.gui.simple.Button.onClick(Button.java:27) ~[?:?]
    at de.codingair.warpsystem.lib.codingapi.player.gui.GUIListener.onInvClickEvent(GUIListener.java:266) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor250.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
    ... 15 more
```

same config works without errors on a Paper **1.16.5** server.

**To Reproduce**
Click on an ActionIcon when running WarpSystem on a 1.12.2 Paper server.

**Expected behavior**
ActionIcon is "executed" if it is a page, it is opened.

**Comment by rugter100** [comment]
i hve the same issue/error when creating/editting a portal. Could this be related?

**Comment by CodingAir** [comment]
Yes

**Comment by erikzimmermann** [comment]
> i hve the same issue/error when creating/editting a portal. Could this be related?

Yes
