### ISSUE TITLE
[Settings files damaged] Errors are generated on boot on Spigot 1.18.1

### ISSUE THREAD

**Issue by PIBM** [erikzimmermann/WarpSystem-IssueTracker#681]
**Describe the bug**
I've built Spigot 1.18.1, and used only this plugin, without any configuration file, and errors are generated on boot. The configuration files are not written correctly

**To Reproduce**
1. Build Spigot 1.18.1
2. Install WarpSystem 5.0.7-Hotfix 3
3. See error

**Expected behavior**
Booting a fresh install should not result in errors.

**Screenshots**
```
[09:55:16] [Server thread/INFO]: [WarpSystem] Enabling WarpSystem v5.0.7_Hotfix-3
[09:55:16] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: could not determine a constructor for the tag tag:yaml.org,2002:org.bukkit.configuration.MemorySection
[09:55:16] [Server thread/WARN]:  in 'string', line 1, column 13:
[09:55:16] [Server thread/WARN]:     WarpSystem: !!org.bukkit.configuration.Memor ...
[09:55:16] [Server thread/WARN]:                 ^
[09:55:16] [Server thread/WARN]:
[09:55:16] [Server thread/WARN]:        at de.codingair.warpsystem.lib.codingapi.files.loader.UTFConfig.loadFromString(UTFConfig.java:180)
[09:55:16] [Server thread/WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[09:55:16] [Server thread/WARN]:        at de.codingair.warpsystem.lib.codingapi.files.loader.UTFConfig.load(UTFConfig.java:165)
[09:55:16] [Server thread/WARN]:        at de.codingair.warpsystem.lib.codingapi.files.ConfigFile.loadConfig(ConfigFile.java:121)
[09:55:16] [Server thread/WARN]:        at de.codingair.warpsystem.lib.codingapi.files.ConfigFile.<init>(ConfigFile.java:46)
[09:55:16] [Server thread/WARN]:        at de.codingair.warpsystem.lib.codingapi.files.FileManager.loadFile(FileManager.java:62)
[09:55:16] [Server thread/WARN]:        at de.codingair.warpsystem.lib.codingapi.files.FileManager.loadFile(FileManager.java:55)
[09:55:16] [Server thread/WARN]:        at de.codingair.warpsystem.lib.codingapi.files.FileManager.loadFile(FileManager.java:43)
[09:55:16] [Server thread/WARN]:        at de.codingair.warpsystem.spigot.base.WarpSystem.copyConfig(WarpSystem.java:328)
[09:55:16] [Server thread/WARN]:        at de.codingair.warpsystem.spigot.base.WarpSystem.onEnable(WarpSystem.java:130)
[09:55:16] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:55:16] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[09:55:16] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[09:55:16] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:526)
[09:55:16] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:440)
[09:55:16] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612)
[09:55:16] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[09:55:16] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262)
[09:55:16] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994)
[09:55:16] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[09:55:16] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[09:55:16] [Server thread/WARN]: Caused by: could not determine a constructor for the tag tag:yaml.org,2002:org.bukkit.configuration.MemorySection
[09:55:16] [Server thread/WARN]:  in 'string', line 1, column 13:
[09:55:16] [Server thread/WARN]:     WarpSystem: !!org.bukkit.configuration.Memor ...
[09:55:16] [Server thread/WARN]:                 ^
[09:55:16] [Server thread/WARN]:
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:574)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[09:55:16] [Server thread/WARN]:        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:39)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:174)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:158)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
[09:55:16] [Server thread/WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[09:55:16] [Server thread/WARN]:        at de.codingair.warpsystem.lib.codingapi.files.loader.UTFConfig.loadFromString(UTFConfig.java:178)
[09:55:16] [Server thread/WARN]:        ... 20 more
```

**Additional context**
It has been happening on multiple words I tried it for.

**Discord contact**: PIBM#8160

**Comment by PIBM** [comment]
Also, users lose their saved warps on every restart.

**Comment by erikzimmermann** [comment]
Works fine for me...

**Comment by erikzimmermann** [comment]
I'll release a new version very soon. Would be awesome if you try that one.

**Comment by PIBM** [comment]
Definitely, I'm keeping an eye on your builds :)

**Comment by Davie3** [comment]
I am having the same issue as well on v5.0.7 and v5.0.8 - Spigot 1.18.1. I think the issue is an upgrade in the config file from 5.0.6 or maybe lower versions. My config.yml seemed to have been wiped out and contains errors:

Config.yml From 5.0.6 -> 5.0.7: [Config yml (5-0-6 to 5-0-7).txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/7858648/Config.yml.5-0-6.to.5-0-7.txt)
Config.yml From 5.0.6 -> 5.0.8: [Config yml (5-0-6 to 5-0-8).txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/7858655/Config.yml.5-0-6.to.5-0-8.txt)
 
It also seems like files in the Memory folder are also wiped out including Teleporters.yml.

**Comment by erikzimmermann** [comment]
> I am having the same issue as well on v5.0.7 and v5.0.8 - Spigot 1.18.1. I think the issue is an upgrade in the config file from 5.0.6 or maybe lower versions. My config.yml seemed to have been wiped out and contains errors:
> 
> 
> 
> Config.yml From 5.0.6 -> 5.0.7: [Config yml (5-0-6 to 5-0-7).txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/7858648/Config.yml.5-0-6.to.5-0-7.txt)
> 
> Config.yml From 5.0.6 -> 5.0.8: [Config yml (5-0-6 to 5-0-8).txt](https://github.com/CodingAir/WarpSystem-IssueTracker/files/7858655/Config.yml.5-0-6.to.5-0-8.txt)
> 
>  
> 
> It also seems like files in the Memory folder are also wiped out including Teleporters.yml.

Try to remove the WarpSystem folder. All configs should be created correctly then.

**Comment by PIBM** [comment]
As I've explained on the chat, I've also done so (removing all configs) multiple times. I also kept only your plugin, and it is still generating the incorrect files. Is there some data saved on the players or somewhere else that could cause this ?

**Comment by KKYH246** [comment]
my configs (at least the memory part) keeps resetting too no matter whether is it 5.0.7 or 8.
only happens to servers running on 1.18.1
