### ISSUE TITLE
[Name] Plugin doesnt work (error)

### ISSUE THREAD

**Issue by NockyCZ** [erikzimmermann/WarpSystem-IssueTracker#699]
Hi, i have this error in Warp System Premium

```
java.lang.IllegalStateException: Unable to find method set ([class java.lang.String, interface net.minecraft.server.v1_13_R2.NBTBase]).
    at de.codingair.warpsystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:179)
    at de.codingair.warpsystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:177)
    at de.codingair.warpsystem.lib.codingapi.tools.nbt.NBTTagCompound.initialize(NBTTagCompound.java:54)
    at de.codingair.warpsystem.lib.codingapi.tools.nbt.NBTTagCompound.<init>(NBTTagCompound.java:22)
    at de.codingair.warpsystem.lib.codingapi.tools.items.ItemBuilder.<init>(ItemBuilder.java:81)
    at de.codingair.warpsystem.lib.codingapi.tools.items.ItemBuilder.<init>(ItemBuilder.java:70)
    at de.codingair.warpsystem.spigot.features.warps.managers.IconManager.load(IconManager.java:74)
    at de.codingair.warpsystem.spigot.base.managers.DataManager.load(DataManager.java:59)
    at de.codingair.warpsystem.spigot.base.WarpSystem.onEnable(WarpSystem.java:177)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
    at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
    at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
    at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
    at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
    at java.lang.Thread.run(Thread.java:748)```

**Comment by erikzimmermann** [comment]
Fixed.
