### ISSUE TITLE
[Teleports] Teleports don't work

### ISSUE THREAD

**Issue by amarillonmc** [erikzimmermann/WarpSystem-IssueTracker#703]
**Describe the bug**
Updated the server and plugin from 1.16 to 1.18.2.
All previous set warps (be it from a portal or a warp command) stop working

**To Reproduce**
1. Go into a previous made portal or type a /warp command
2. Player didn't warp, following error log is produced

`[09:20:22 INFO]: Amarillo_NMC issued server command: /warp SkylandSpawn
[09:20:22 WARN]: [WarpSystem] Task #1694 for WarpSystem v5.1.0-free generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "de.codingair.warpsystem.spigot.base.utils.options.Option.getValue()" is null
        at de.codingair.warpsystem.spigot.base.utils.options.specific.GeneralOptions.isSafeTp(GeneralOptions.java:317) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.destinations.Options.isSafeTP(Options.java:172) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.destinations.DestinationAdapter.prepare(DestinationAdapter.java:33) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.destinations.adapters.SimpleWarpAdapter.teleport(SimpleWarpAdapter.java:41) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.destinations.Destination.teleport(Destination.java:126) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.PlayerTeleport.start(PlayerTeleport.java:108) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.TeleportStage.end(TeleportStage.java:87) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.TeleportDelay.end(TeleportDelay.java:92) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.TeleportDelay.start(TeleportDelay.java:39) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.TeleportStage.end(TeleportStage.java:87) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.ConfirmPayment$4.accept(ConfirmPayment.java:117) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.ConfirmPayment$4.accept(ConfirmPayment.java:114) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.ConfirmPayment.confirm(ConfirmPayment.java:28) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.ConfirmPayment.start(ConfirmPayment.java:114) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.TeleportStage.end(TeleportStage.java:87) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.WaitForTeleport.start(WaitForTeleport.java:67) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.TeleportStage.end(TeleportStage.java:87) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.SimulateStage.start(SimulateStage.java:41) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.TeleportStage.begin(TeleportStage.java:40) ~[WarpSystem_v5.1.0-free.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.Teleport.lambda$null$0(Teleport.java:61) ~[WarpSystem_v5.1.0-free.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-379]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Expected behavior**
Player should warp to the given warp.

**Screenshots**
N/A, see error logs above.

**Additional context**
N/A

**Discord contact**: nemoma#0001

**Comment by erikzimmermann** [comment]
Please delete you `config.yml` and let a the plugin create a new one. That should fix your issue. 
Please bump this issue if this hasn't fixed it.
