### ISSUE TITLE
[player warps] When using 1.19 items to set pwarp appearance the server crash

### ISSUE THREAD

**Issue by rm20killer** [erikzimmermann/WarpSystem-IssueTracker#717]
**Describe the bug**
When chaning the appearance the server crashes if that item in a 1.19 block.
Error before the server stops
```
[21:30:09] [Server thread/ERROR]: Could not pass event InventoryClickEvent to WarpSystem v5.1.2
java.lang.IllegalArgumentException: Unsupported material with no data value: SCULK
    at de.codingair.warpsystem.lib.codingapi.tools.items.XMaterial.lambda$matchXMaterial$0(XMaterial.java:1676) ~[WarpSystem_v5.1.2.jar:?]
    at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
    at de.codingair.warpsystem.lib.codingapi.tools.items.XMaterial.matchXMaterial(XMaterial.java:1676) ~[WarpSystem_v5.1.2.jar:?]
    at de.codingair.warpsystem.lib.codingapi.tools.items.ItemBuilder.setData(ItemBuilder.java:802) ~[WarpSystem_v5.1.2.jar:?]
    at de.codingair.warpsystem.spigot.features.playerwarps.utils.PlayerWarp.changeItem(PlayerWarp.java:404) ~[WarpSystem_v5.1.2.jar:?]
    at de.codingair.warpsystem.spigot.features.playerwarps.guis.editor.pages.PAppearance$1.onClick(PAppearance.java:97) ~[WarpSystem_v5.1.2.jar:?]
    at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.gui.simple.Button.onClick(Button.java:27) ~[WarpSystem_v5.1.2.jar:?]
    at de.codingair.warpsystem.lib.codingapi.player.gui.GUIListener.onInvClickEvent(GUIListener.java:259) ~[WarpSystem_v5.1.2.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor603.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-112]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3304) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
    at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-112]
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.2.jar:git-Paper-112]
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-112]
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.2.jar:git-Paper-112]
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.2.jar:git-Paper-112]
    at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1463) ~[paper-1.19.2.jar:git-Paper-112]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.2.jar:git-Paper-112]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-112]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
After that error displays around a min the server stops it self.

**To Reproduce**
1. Hold any 1.19 block 
2. Do the command `/pwarps edit (warp name)`
3. Click on the item to change the appearance
4. Watch the server close it self

**Expected behavior**
The item should apear as the item appearance without casuing the server to crash

**Additional context**
Using paper 112 
Behind waterfall 504
WIth warpSystem 5.1.2-Premium
**Discord contact**: RM20#2000

**Comment by JohnsanGeezo** [comment]
I had this as well, for Sculk catalysts and propagules, but it hasn't crashed my server yet.
https://pastebin.com/pYC4Pwgk
