### ISSUE TITLE
WarpSystem v5.1.3_Hotfix-4 - Sign descrtiption not possible - Paper 1.19.3

### ISSUE THREAD

**Issue by karlheidar** [erikzimmermann/WarpSystem-IssueTracker#730]
**Describe the bug**
I have created a new sign, and global warp destination. This works, and clicking the sign works. However when i try to edit the sign the editor exits, and no sign description is possible.

**To Reproduce**
1. Create sign
2. Click on Destination
3. Click on Edit sign

**Expected behavior**
The sign will create with destination set, but no description of the sign is possible.

**Discord contact**: Mc_VaDeR#0042

** Code from multicraft console:

23.12 13:36:11 [Server] WARN [WarpSystem] Task #142 for WarpSystem v5.1.3_Hotfix-4 generated an exception
23.12 13:36:11 [Server] INFO java.lang.IllegalStateException: Cannot use reflection.
23.12 13:36:11 [Server] INFO at de.codingair.warpsystem.lib.codingapi.server.reflections.IReflection$5.set(IReflection.java:241) ~[WarpSystem_v5.1.3_Hotfix-4.jar:?]
23.12 13:36:11 [Server] INFO at de.codingair.warpsystem.lib.codingapi.player.gui.sign.SignGUI.prepareSignEditing(SignGUI.java:276) ~[WarpSystem_v5.1.3_Hotfix-4.jar:?]
23.12 13:36:11 [Server] INFO at de.codingair.warpsystem.lib.codingapi.player.gui.sign.SignGUI.lambda$open$1(SignGUI.java:119) ~[WarpSystem_v5.1.3_Hotfix-4.jar:?]
23.12 13:36:11 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-353]
23.12 13:36:11 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-353]
23.12 13:36:11 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-353]
23.12 13:36:11 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-353]
23.12 13:36:11 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-353]
23.12 13:36:11 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-353]
23.12 13:36:11 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-353]
23.12 13:36:11 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
23.12 13:36:11 [Server] INFO Caused by: java.lang.IllegalAccessException: Can not set static final boolean field net.minecraft.world.level.block.entity.TileEntitySign.CONVERT_LEGACY_SIGNS to java.lang.Boolean
23.12 13:36:11 [Server] INFO at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76) ~[?:?]
23.12 13:36:11 [Server] INFO at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80) ~[?:?]
23.12 13:36:11 [Server] INFO at jdk.internal.reflect.UnsafeQualifiedStaticBooleanFieldAccessorImpl.set(UnsafeQualifiedStaticBooleanFieldAccessorImpl.java:77) ~[?:?]
23.12 13:36:11 [Server] INFO at java.lang.reflect.Field.set(Field.java:799) ~[?:?]
23.12 13:36:11 [Server] INFO at de.codingair.warpsystem.lib.codingapi.server.reflections.IReflection$5.set(IReflection.java:239) ~[WarpSystem_v5.1.3_Hotfix-4.jar:?]
23.12 13:36:11 [Server] INFO ... 10 more

**Comment by karlheidar** [comment]
Confirmed, Hotfix-5 fixed this issue.
