### ISSUE TITLE
[player warps Bug] Can't set warp item to 1.20 items

### ISSUE THREAD

**Issue by rm20killer** [erikzimmermann/WarpSystem-IssueTracker#757]
**Describe the bug**
Can't set warp item to 1.20 items

error
```
[15:13:03] [Server thread/ERROR]: Could not pass event InventoryClickEvent to WarpSystem v5.1.7
java.lang.IllegalArgumentException: Unsupported material with no data value: CHERRY_SAPLING
	at de.codingair.warpsystem.lib.codingapi.tools.items.XMaterial.lambda$matchXMaterial$0(XMaterial.java:1691) ~[WarpSystem_v5.1.7_1.20.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at de.codingair.warpsystem.lib.codingapi.tools.items.XMaterial.matchXMaterial(XMaterial.java:1691) ~[WarpSystem_v5.1.7_1.20.jar:?]
	at de.codingair.warpsystem.lib.codingapi.tools.items.ItemBuilder.setData(ItemBuilder.java:802) ~[WarpSystem_v5.1.7_1.20.jar:?]
	at de.codingair.warpsystem.spigot.features.playerwarps.utils.PlayerWarp.changeItem(PlayerWarp.java:404) ~[WarpSystem_v5.1.7_1.20.jar:?]
	at de.codingair.warpsystem.spigot.features.playerwarps.guis.editor.pages.PAppearance$1.onClick(PAppearance.java:97) ~[WarpSystem_v5.1.7_1.20.jar:?]
	at de.codingair.warpsystem.lib.codingapi.player.gui.inventory.gui.simple.Button.onClick(Button.java:27) ~[WarpSystem_v5.1.7_1.20.jar:?]
	at de.codingair.warpsystem.lib.codingapi.player.gui.GUIListener.onInvClickEvent(GUIListener.java:268) ~[WarpSystem_v5.1.7_1.20.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor580.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-117]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-117]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3245) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1386) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-117]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**To Reproduce**
1. Hold any 1.19 block
2. Do the command /pwarps edit (warp name)
3. Click on the item to change the appearance
4. see error and item not change

**Expected behavior**
The item should appear as the item appearance 

**Additional context**
Paper 1.20 #119 
behind waterfall 536
using warpsystem v5.1.7 Premium

**Discord contact**: RM20

**Comment by erikzimmermann** [comment]
Fixed with v5.1.8
