### ISSUE TITLE
[Warps bug] Log error on warp

### ISSUE THREAD

**Issue by Flipsss12** [erikzimmermann/WarpSystem-IssueTracker#758]
**Describe the bug**
When a player teleports with /warps I have an error in the logs which repeats in a loop.

Error:
```
[13:12:22] [Server thread/WARN]: [WarpSystem] Task #595 for WarpSystem v5.1.8-free generated an exception
java.lang.NoClassDefFoundError: Could not initialize class de.codingair.warpsystem.lib.codingapi.particles.ParticlePacket
	at de.codingair.warpsystem.lib.codingapi.particles.Particle.getParticlePacket(Particle.java:340) ~[WarpSystem_v5.1.8-free.jar:?]
	at de.codingair.warpsystem.spigot.base.utils.effects.RotatingParticleSpiral.run(RotatingParticleSpiral.java:53) ~[WarpSystem_v5.1.8-free.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-248]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-248]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-248]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-248]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-248]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-248]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-248]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```
**To Reproduce**
1. Use /warps
2. Click on a warp item
3. See error in log

**Additional context**
Paper v1.20.2-248
WarpSystem v5.1.8 Free

**Comment by Parthodys** [comment]
This needs a fix asap, log files are bloating to multiple gigabytes and console is basically unusable.
