### ISSUE TITLE
[Warp particle exception] <NoClassDefFoundErrorCould spam in console>

### ISSUE THREAD

**Issue by flakysalt** [erikzimmermann/WarpSystem-IssueTracker#760]
**Describe the bug**
After a restart, the console repeatedly receives the same error as soon as the first player uses a warp. This compromises server performance after some hours of uptime.

**To Reproduce**
1. Start the server
2. Warp to any existing warp on the server
3. See error in server console

**Expected behavior**
There should be no error being spammed

**Error**
[12.11 21:57:23] [Server] [WARN] [WarpSystem] Task #52 for WarpSystem v5.1.8-free generated an exception
[12.11 21:57:23] [Server] java.lang.NoClassDefFoundErrorCould not initialize class de.codingair.warpsystem.lib.codingapi.particles.ParticlePacket
[12.11 21:57:23] [Server] 	at de.codingair.warpsystem.lib.codingapi.particles.Particle.getParticlePacket(Particle.java:340) ~[WarpSystem_v5.1.8-free.jar:?]
[12.11 21:57:23] [Server] 	at de.codingair.warpsystem.spigot.base.utils.effects.RotatingParticleSpiral.run(RotatingParticleSpiral.java:53) ~[WarpSystem_v5.1.8-free.jar:?]
[12.11 21:57:23] [Server] 	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-290]
[12.11 21:57:23] [Server] 	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-290]
[12.11 21:57:23] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-290]
[12.11 21:57:23] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-290]
[12.11 21:57:23] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-290]
[12.11 21:57:23] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-290]
[12.11 21:57:23] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-290]
[12.11 21:57:23] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12.11 21:57:23] [Server] Caused byjava.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Unable to find method toNMS ([class org.bukkit.Particle, class java.lang.Object]). [in thread "Server thread"]
[12.11 21:57:23] [Server] 	at de.codingair.warpsystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:176) ~[WarpSystem_v5.1.8-free.jar:?]
[12.11 21:57:23] [Server] 	at de.codingair.warpsystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:174) ~[WarpSystem_v5.1.8-free.jar:?]

**Additional context**
Paper Version:  git-Paper-290 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: f186318)

**Discord contact**: @flakysalt

**Comment by braceyourself07** [comment]
This is the same as #758 which I think the dev fixed in hotfix 1 that was released on Nov 2.  You can get the link in their support Discord

**Comment by erikzimmermann** [comment]
@braceyourself07 is right. Thanks for pointing that out 👍🏻
